version: "3"

services:
  code_forwarding_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "python main.py"
    container_name: code-forwarding
